#!/usr/bin/env bash
# Generated by project-knowledge-bootstrap v1.0
# Version: 1.1
# Setup AI Skills for project development
# Configures AI coding assistants that follow agentskills.io standard:
#   - Claude Code: .claude/skills/ symlink + CLAUDE.md copies
#   - Cursor:      .cursor/skills/ symlink + .cursorrules copy
#   - OpenCode:    .opencode/skills/ symlink (uses AGENTS.md natively)
#   - Gemini CLI:  .gemini/skills/ symlink + GEMINI.md copies
#   - GitHub Copilot: .github/copilot-instructions.md copy
#
# Usage:
#   ./setup.sh                  # Interactive mode (select AI assistants)
#   ./setup.sh --all            # Configure all AI assistants (project)
#   ./setup.sh --all --global   # Configure all AI assistants (global)
#   ./setup.sh --claude         # Configure only Claude Code
#   ./setup.sh --claude --cursor --global  # Global setup for Claude + Cursor
#
# Compatible with Bash 3+ (macOS default)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
SKILLS_SOURCE="$SCRIPT_DIR"

# Project name (derived from repo root directory name)
PROJECT_NAME="$(basename "$REPO_ROOT")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Selection flags
SETUP_CLAUDE=false
SETUP_CURSOR=false
SETUP_OPENCODE=false
SETUP_GEMINI=false
SETUP_COPILOT=false
SETUP_GLOBAL=false

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Configure AI coding assistants for $PROJECT_NAME development."
    echo ""
    echo "Options:"
    echo "  --all       Configure all AI assistants"
    echo "  --global    Install globally (~/) instead of project (./)"
    echo "  --claude    Configure Claude Code"
    echo "  --cursor    Configure Cursor"
    echo "  --opencode  Configure OpenCode"
    echo "  --gemini    Configure Gemini CLI"
    echo "  --copilot   Configure GitHub Copilot"
    echo "  --help      Show this help message"
    echo ""
    echo "If no options provided, runs in interactive mode."
    echo ""
    echo "Examples:"
    echo "  $0                          # Interactive selection (project)"
    echo "  $0 --all                    # All AI assistants (project)"
    echo "  $0 --all --global           # All AI assistants (global)"
    echo "  $0 --claude --cursor        # Only Claude and Cursor (project)"
    echo "  $0 --claude --cursor --global  # Only Claude and Cursor (global)"
}

show_menu() {
    local scope_label="project"
    [ "$SETUP_GLOBAL" = true ] && scope_label="global"

    echo -e "${BOLD}Which AI assistants do you use? ($scope_label)${NC}"
    echo -e "${CYAN}(Use numbers to toggle, Enter to confirm)${NC}"
    echo ""

    local options=("Claude Code" "Cursor" "OpenCode" "Gemini CLI" "GitHub Copilot")
    local selected=(true false false false false)  # Claude selected by default

    while true; do
        for i in "${!options[@]}"; do
            if [ "${selected[$i]}" = true ]; then
                echo -e "  ${GREEN}[x]${NC} $((i+1)). ${options[$i]}"
            else
                echo -e "  [ ] $((i+1)). ${options[$i]}"
            fi
        done
        echo ""
        echo -e "  ${YELLOW}a${NC}. Select all"
        echo -e "  ${YELLOW}n${NC}. Select none"
        echo ""
        echo -n "Toggle (1-5, a, n) or Enter to confirm: "

        read -r choice

        case $choice in
            1) selected[0]=$([ "${selected[0]}" = true ] && echo false || echo true) ;;
            2) selected[1]=$([ "${selected[1]}" = true ] && echo false || echo true) ;;
            3) selected[2]=$([ "${selected[2]}" = true ] && echo false || echo true) ;;
            4) selected[3]=$([ "${selected[3]}" = true ] && echo false || echo true) ;;
            5) selected[4]=$([ "${selected[4]}" = true ] && echo false || echo true) ;;
            a|A) selected=(true true true true true) ;;
            n|N) selected=(false false false false false) ;;
            "") break ;;
            *) echo -e "${RED}Invalid option${NC}" ;;
        esac

        # Move cursor up to redraw menu
        echo -en "\033[11A\033[J"
    done

    SETUP_CLAUDE=${selected[0]}
    SETUP_CURSOR=${selected[1]}
    SETUP_OPENCODE=${selected[2]}
    SETUP_GEMINI=${selected[3]}
    SETUP_COPILOT=${selected[4]}
}

# Create symlink for skills directory
# $1 = target directory (e.g., .claude/skills or ~/.claude/skills)
# $2 = parent directory to create if missing (e.g., .claude or ~/.claude)
create_skills_symlink() {
    local target="$1"
    local parent="$2"

    if [ ! -d "$parent" ]; then
        mkdir -p "$parent"
    fi

    if [ -L "$target" ]; then
        rm "$target"
    elif [ -d "$target" ]; then
        mv "$target" "${target}.backup.$(date +%s)"
        echo -e "${YELLOW}  ! Existing skills/ backed up${NC}"
    fi

    ln -s "$SKILLS_SOURCE" "$target"
}

# Copy all AGENTS.md files to a tool-specific name
# $1 = target filename (e.g., CLAUDE.md, GEMINI.md)
# $2 = root search path (REPO_ROOT or HOME)
copy_agents_md() {
    local target_name="$1"
    local search_root="$2"
    local count=0

    # Use a while-read loop to avoid word splitting issues (Bash 3 safe)
    while IFS= read -r agents_file; do
        [ -z "$agents_file" ] && continue
        local agents_dir
        agents_dir=$(dirname "$agents_file")
        cp "$agents_file" "$agents_dir/$target_name"
        count=$((count + 1))
    done <<EOF
$(find "$search_root" -maxdepth 2 -name "AGENTS.md" -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/vendor/*" -not -path "*/.next/*" -not -path "*/dist/*" -not -path "*/.claude/*" -not -path "*/.cursor/*" -not -path "*/.gemini/*" 2>/dev/null)
EOF

    if [ "$count" -gt 0 ]; then
        echo -e "${GREEN}  ✓ Copied $count AGENTS.md -> $target_name${NC}"
    else
        echo -e "${YELLOW}  ! No AGENTS.md files found to copy${NC}"
    fi
}

# =============================================================================
# TOOL-SPECIFIC SETUP FUNCTIONS
# =============================================================================

setup_claude() {
    if [ "$SETUP_GLOBAL" = true ]; then
        local target="$HOME/.claude/skills"
        create_skills_symlink "$target" "$HOME/.claude"
        echo -e "${GREEN}  ✓ ~/.claude/skills -> $SKILLS_SOURCE${NC}"

        if [ -f "$REPO_ROOT/AGENTS.md" ]; then
            cp "$REPO_ROOT/AGENTS.md" "$HOME/CLAUDE.md"
            echo -e "${GREEN}  ✓ AGENTS.md -> ~/CLAUDE.md${NC}"
        else
            echo -e "${YELLOW}  ! No AGENTS.md found to copy${NC}"
        fi
    else
        local target="$REPO_ROOT/.claude/skills"
        create_skills_symlink "$target" "$REPO_ROOT/.claude"
        echo -e "${GREEN}  ✓ .claude/skills -> skills/${NC}"
        copy_agents_md "CLAUDE.md" "$REPO_ROOT"
    fi
}

setup_cursor() {
    if [ "$SETUP_GLOBAL" = true ]; then
        local target="$HOME/.cursor/skills"
        create_skills_symlink "$target" "$HOME/.cursor"
        echo -e "${GREEN}  ✓ ~/.cursor/skills -> $SKILLS_SOURCE${NC}"

        # Cursor uses .cursorrules at home when global
        if [ -f "$REPO_ROOT/AGENTS.md" ]; then
            cp "$REPO_ROOT/AGENTS.md" "$HOME/.cursorrules"
            echo -e "${GREEN}  ✓ AGENTS.md -> ~/.cursorrules${NC}"
        fi
    else
        local target="$REPO_ROOT/.cursor/skills"
        create_skills_symlink "$target" "$REPO_ROOT/.cursor"
        echo -e "${GREEN}  ✓ .cursor/skills -> skills/${NC}"

        # Cursor uses .cursorrules at repo root
        if [ -f "$REPO_ROOT/AGENTS.md" ]; then
            cp "$REPO_ROOT/AGENTS.md" "$REPO_ROOT/.cursorrules"
            echo -e "${GREEN}  ✓ AGENTS.md -> .cursorrules${NC}"
        fi
    fi
}

setup_opencode() {
    if [ "$SETUP_GLOBAL" = true ]; then
        local target="$HOME/.config/opencode/skills"
        create_skills_symlink "$target" "$HOME/.config/opencode"
        echo -e "${GREEN}  ✓ ~/.config/opencode/skills -> $SKILLS_SOURCE${NC}"
        echo -e "${GREEN}  ✓ OpenCode uses AGENTS.md natively${NC}"
    else
        local target="$REPO_ROOT/.opencode/skills"
        create_skills_symlink "$target" "$REPO_ROOT/.opencode"
        echo -e "${GREEN}  ✓ .opencode/skills -> skills/${NC}"
        echo -e "${GREEN}  ✓ OpenCode uses AGENTS.md natively${NC}"
    fi
}

setup_gemini() {
    if [ "$SETUP_GLOBAL" = true ]; then
        local target="$HOME/.gemini/skills"
        create_skills_symlink "$target" "$HOME/.gemini"
        echo -e "${GREEN}  ✓ ~/.gemini/skills -> $SKILLS_SOURCE${NC}"

        if [ -f "$REPO_ROOT/AGENTS.md" ]; then
            cp "$REPO_ROOT/AGENTS.md" "$HOME/GEMINI.md"
            echo -e "${GREEN}  ✓ AGENTS.md -> ~/GEMINI.md${NC}"
        else
            echo -e "${YELLOW}  ! No AGENTS.md found to copy${NC}"
        fi
    else
        local target="$REPO_ROOT/.gemini/skills"
        create_skills_symlink "$target" "$REPO_ROOT/.gemini"
        echo -e "${GREEN}  ✓ .gemini/skills -> skills/${NC}"
        copy_agents_md "GEMINI.md" "$REPO_ROOT"
    fi
}

setup_copilot() {
    if [ "$SETUP_GLOBAL" = true ]; then
        # Copilot doesn't have a well-supported global config path
        echo -e "${YELLOW}  ! GitHub Copilot setup is project-only. Skipping global.${NC}"
        return 0
    fi

    if [ -f "$REPO_ROOT/AGENTS.md" ]; then
        mkdir -p "$REPO_ROOT/.github"
        cp "$REPO_ROOT/AGENTS.md" "$REPO_ROOT/.github/copilot-instructions.md"
        echo -e "${GREEN}  ✓ AGENTS.md -> .github/copilot-instructions.md${NC}"
    else
        echo -e "${YELLOW}  ! No root AGENTS.md found for Copilot${NC}"
    fi
}

# =============================================================================
# PARSE ARGUMENTS
# =============================================================================

while [ $# -gt 0 ]; do
    case $1 in
        --all)
            SETUP_CLAUDE=true
            SETUP_CURSOR=true
            SETUP_OPENCODE=true
            SETUP_GEMINI=true
            SETUP_COPILOT=true
            shift
            ;;
        --global)
            SETUP_GLOBAL=true
            shift
            ;;
        --claude)
            SETUP_CLAUDE=true
            shift
            ;;
        --cursor)
            SETUP_CURSOR=true
            shift
            ;;
        --opencode)
            SETUP_OPENCODE=true
            shift
            ;;
        --gemini)
            SETUP_GEMINI=true
            shift
            ;;
        --copilot)
            SETUP_COPILOT=true
            shift
            ;;
        --help|-h)
            show_help
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            show_help
            exit 1
            ;;
    esac
done

# =============================================================================
# MAIN
# =============================================================================

local_scope="project"
[ "$SETUP_GLOBAL" = true ] && local_scope="global"

echo ""
echo -e "${BOLD}AI Skills Setup — $PROJECT_NAME ($local_scope)${NC}"
echo "========================================"
echo ""

# Count skills
SKILL_COUNT=0
while IFS= read -r _skill_file; do
    [ -z "$_skill_file" ] && continue
    SKILL_COUNT=$((SKILL_COUNT + 1))
done <<EOF
$(find "$SKILLS_SOURCE" -mindepth 2 -maxdepth 2 -name "SKILL.md" 2>/dev/null)
EOF

if [ "$SKILL_COUNT" -eq 0 ]; then
    echo -e "${RED}No skills found in $SKILLS_SOURCE${NC}"
    exit 1
fi

echo -e "${BLUE}Found $SKILL_COUNT skills to configure${NC}"
echo ""

# Interactive mode if no flags provided
if [ "$SETUP_CLAUDE" = false ] && [ "$SETUP_CURSOR" = false ] && \
   [ "$SETUP_OPENCODE" = false ] && [ "$SETUP_GEMINI" = false ] && \
   [ "$SETUP_COPILOT" = false ]; then
    show_menu
    echo ""
fi

# Check if at least one selected
if [ "$SETUP_CLAUDE" = false ] && [ "$SETUP_CURSOR" = false ] && \
   [ "$SETUP_OPENCODE" = false ] && [ "$SETUP_GEMINI" = false ] && \
   [ "$SETUP_COPILOT" = false ]; then
    echo -e "${YELLOW}No AI assistants selected. Nothing to do.${NC}"
    exit 0
fi

# Count selected
STEP=1
TOTAL=0
[ "$SETUP_CLAUDE" = true ] && TOTAL=$((TOTAL + 1))
[ "$SETUP_CURSOR" = true ] && TOTAL=$((TOTAL + 1))
[ "$SETUP_OPENCODE" = true ] && TOTAL=$((TOTAL + 1))
[ "$SETUP_GEMINI" = true ] && TOTAL=$((TOTAL + 1))
[ "$SETUP_COPILOT" = true ] && TOTAL=$((TOTAL + 1))

# Run selected setups
if [ "$SETUP_CLAUDE" = true ]; then
    echo -e "${YELLOW}[$STEP/$TOTAL] Setting up Claude Code...${NC}"
    setup_claude
    echo ""
    STEP=$((STEP + 1))
fi

if [ "$SETUP_CURSOR" = true ]; then
    echo -e "${YELLOW}[$STEP/$TOTAL] Setting up Cursor...${NC}"
    setup_cursor
    echo ""
    STEP=$((STEP + 1))
fi

if [ "$SETUP_OPENCODE" = true ]; then
    echo -e "${YELLOW}[$STEP/$TOTAL] Setting up OpenCode...${NC}"
    setup_opencode
    echo ""
    STEP=$((STEP + 1))
fi

if [ "$SETUP_GEMINI" = true ]; then
    echo -e "${YELLOW}[$STEP/$TOTAL] Setting up Gemini CLI...${NC}"
    setup_gemini
    echo ""
    STEP=$((STEP + 1))
fi

if [ "$SETUP_COPILOT" = true ]; then
    echo -e "${YELLOW}[$STEP/$TOTAL] Setting up GitHub Copilot...${NC}"
    setup_copilot
    echo ""
fi

# =============================================================================
# SUMMARY
# =============================================================================

echo -e "${GREEN}Done! Configured $SKILL_COUNT AI skills.${NC}"
echo ""
echo "Configured ($local_scope):"
if [ "$SETUP_GLOBAL" = true ]; then
    [ "$SETUP_CLAUDE" = true ] && echo "  - Claude Code:    ~/.claude/skills/ + ~/CLAUDE.md"
    [ "$SETUP_CURSOR" = true ] && echo "  - Cursor:         ~/.cursor/skills/ + ~/.cursorrules"
    [ "$SETUP_OPENCODE" = true ] && echo "  - OpenCode:       ~/.config/opencode/skills/"
    [ "$SETUP_GEMINI" = true ] && echo "  - Gemini CLI:     ~/.gemini/skills/ + ~/GEMINI.md"
    [ "$SETUP_COPILOT" = true ] && echo "  - GitHub Copilot: project-only (skipped globally)"
else
    [ "$SETUP_CLAUDE" = true ] && echo "  - Claude Code:    .claude/skills/ + CLAUDE.md"
    [ "$SETUP_CURSOR" = true ] && echo "  - Cursor:         .cursor/skills/ + .cursorrules"
    [ "$SETUP_OPENCODE" = true ] && echo "  - OpenCode:       .opencode/skills/ + AGENTS.md (native)"
    [ "$SETUP_GEMINI" = true ] && echo "  - Gemini CLI:     .gemini/skills/ + GEMINI.md"
    [ "$SETUP_COPILOT" = true ] && echo "  - GitHub Copilot: .github/copilot-instructions.md"
fi
echo ""
echo -e "${BLUE}Note: Restart your AI assistant to load the skills.${NC}"
echo -e "${BLUE}      AGENTS.md is the source of truth — edit it, then re-run this script.${NC}"
