#!/usr/bin/env bash
# Generated by project-knowledge-bootstrap v1.1.2
# Version: 1.1.2
# Setup AI Skills for project development
# Configures AI coding assistants that follow agentskills.io standard
# On Windows PowerShell/CMD, use setup.ps1 instead.
# Compatible with Bash 3+ (macOS default)

set -e

# Detect Windows environments
IS_WINDOWS=false
USE_COPY=false
if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ -n "$MSYSTEM" ]]; then
    IS_WINDOWS=true
    USE_COPY=true
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
SKILLS_SOURCE="$SCRIPT_DIR"
PROJECT_NAME="$(basename "$REPO_ROOT")"

# ─── Colors ──────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# ─── Flags ───────────────────────────────────────────────────────────
SETUP_CLAUDE=false
SETUP_CURSOR=false
SETUP_OPENCODE=false
SETUP_GEMINI=false
SETUP_COPILOT=false
SETUP_GLOBAL=false

# ─── Helper Functions ────────────────────────────────────────────────

print_banner() {
    local scope_label="project"
    [ "$SETUP_GLOBAL" = true ] && scope_label="global"
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}  🧠  ${BOLD}project-knowledge-bootstrap${NC}                        ${CYAN}║${NC}"
    echo -e "${CYAN}║${NC}     ${DIM}Configure AI assistants for${NC}                        ${CYAN}║${NC}"
    echo -e "${CYAN}║${NC}     ${BOLD}${PROJECT_NAME}${NC} ${DIM}(${scope_label})${NC}                              ${CYAN}║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_box() {
    local color="$1"
    local icon="$2"
    shift 2
    echo -e "${color}┌────────────────────────────────────────────────────────────┐${NC}"
    echo -e "${color}│${NC} ${icon}  $@"
    echo -e "${color}└────────────────────────────────────────────────────────────┘${NC}"
}

show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --all       Configure all AI assistants"
    echo "  --global    Install globally (~/) instead of project (./)"
    echo "  --claude    Configure Claude Code"
    echo "  --cursor    Configure Cursor"
    echo "  --opencode  Configure OpenCode"
    echo "  --gemini    Configure Gemini CLI"
    echo "  --copilot   Configure GitHub Copilot"
    echo "  --help      Show this help message"
}

show_menu() {
    local scope_label="project"
    [ "$SETUP_GLOBAL" = true ] && scope_label="global"

    echo -e "${BOLD}🎛️  Which AI assistants do you use?${NC} ${DIM}($scope_label)${NC}"
    echo -e "${DIM}   (Use numbers to toggle, Enter to confirm)${NC}"
    echo ""

    local options=("🟣 Claude Code" "⚫ Cursor" "🔵 OpenCode" "🔴 Gemini CLI" "🟠 GitHub Copilot")
    local selected=(true false false false false)

    while true; do
        for i in "${!options[@]}"; do
            if [ "${selected[$i]}" = true ]; then
                echo -e "     ${GREEN}[✓]${NC} $((i+1)). ${options[$i]}"
            else
                echo -e "     ${DIM}[ ]${NC} $((i+1)). ${options[$i]}"
            fi
        done
        echo ""
        echo -e "     ${YELLOW}a${NC}. Select all    ${YELLOW}n${NC}. Select none"
        echo ""
        echo -n "   Toggle (1-5, a, n) or press Enter: "
        read -r choice

        case $choice in
            1) selected[0]=$([ "${selected[0]}" = true ] && echo false || echo true) ;;
            2) selected[1]=$([ "${selected[1]}" = true ] && echo false || echo true) ;;
            3) selected[2]=$([ "${selected[2]}" = true ] && echo false || echo true) ;;
            4) selected[3]=$([ "${selected[3]}" = true ] && echo false || echo true) ;;
            5) selected[4]=$([ "${selected[4]}" = true ] && echo false || echo true) ;;
            a|A) selected=(true true true true true) ;;
            n|N) selected=(false false false false false) ;;
            "") break ;;
            *) echo -e "${RED}   Invalid option${NC}" ;;
        esac

        echo -en "\033[10A\033[J"
    done

    SETUP_CLAUDE=${selected[0]}
    SETUP_CURSOR=${selected[1]}
    SETUP_OPENCODE=${selected[2]}
    SETUP_GEMINI=${selected[3]}
    SETUP_COPILOT=${selected[4]}
}

create_skills_symlink() {
    local target="$1"
    local parent="$2"

    [ ! -d "$parent" ] && mkdir -p "$parent"

    if [ -L "$target" ]; then
        rm "$target"
    elif [ -d "$target" ]; then
        mv "$target" "${target}.backup.$(date +%s)"
        echo -e "${YELLOW}     ⚠️  Existing skills/ backed up${NC}"
    fi

    if [ "$USE_COPY" = true ]; then
        cp -r "$SKILLS_SOURCE" "$target"
        echo -e "${GREEN}     📦 Copied${NC} ${DIM}skills/ → $target${NC}"
    else
        ln -s "$SKILLS_SOURCE" "$target"
    fi
}

copy_agents_md() {
    local target_name="$1"
    local search_root="$2"
    local count=0

    while IFS= read -r agents_file; do
        [ -z "$agents_file" ] && continue
        local agents_dir
        agents_dir=$(dirname "$agents_file")
        cp "$agents_file" "$agents_dir/$target_name"
        count=$((count + 1))
    done <<EOF
$(find "$search_root" -maxdepth 2 -name "AGENTS.md" -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/vendor/*" -not -path "*/.next/*" -not -path "*/dist/*" -not -path "*/.claude/*" -not -path "*/.cursor/*" -not -path "*/.gemini/*" 2>/dev/null)
EOF

    if [ "$count" -gt 0 ]; then
        echo -e "${GREEN}     📝 Copied${NC} ${DIM}AGENTS.md → $target_name ($count file(s))${NC}"
    else
        echo -e "${YELLOW}     ⚠️  No AGENTS.md files found to copy${NC}"
    fi
}

# ─── Tool Setup Functions ───────────────────────────────────────────

setup_claude() {
    echo -e "${MAGENTA}   🟣 Claude Code${NC}"
    if [ "$SETUP_GLOBAL" = true ]; then
        create_skills_symlink "$HOME/.claude/skills" "$HOME/.claude"
        [ ! -L "$HOME/.claude/skills" ] && echo -e "${GREEN}     🔗 Symlinked${NC} ${DIM}~/.claude/skills${NC}"
        if [ -f "$REPO_ROOT/AGENTS.md" ]; then
            cp "$REPO_ROOT/AGENTS.md" "$HOME/CLAUDE.md"
            echo -e "${GREEN}     📝 Copied${NC} ${DIM}AGENTS.md → ~/CLAUDE.md${NC}"
        fi
    else
        create_skills_symlink "$REPO_ROOT/.claude/skills" "$REPO_ROOT/.claude"
        [ ! -L "$REPO_ROOT/.claude/skills" ] && echo -e "${GREEN}     🔗 Symlinked${NC} ${DIM}.claude/skills${NC}"
        copy_agents_md "CLAUDE.md" "$REPO_ROOT"
    fi
}

setup_cursor() {
    echo -e "${BOLD}   ⚫ Cursor${NC}"
    if [ "$SETUP_GLOBAL" = true ]; then
        create_skills_symlink "$HOME/.cursor/skills" "$HOME/.cursor"
        [ ! -L "$HOME/.cursor/skills" ] && echo -e "${GREEN}     🔗 Symlinked${NC} ${DIM}~/.cursor/skills${NC}"
        if [ -f "$REPO_ROOT/AGENTS.md" ]; then
            cp "$REPO_ROOT/AGENTS.md" "$HOME/.cursorrules"
            echo -e "${GREEN}     📝 Copied${NC} ${DIM}AGENTS.md → ~/.cursorrules${NC}"
        fi
    else
        create_skills_symlink "$REPO_ROOT/.cursor/skills" "$REPO_ROOT/.cursor"
        [ ! -L "$REPO_ROOT/.cursor/skills" ] && echo -e "${GREEN}     🔗 Symlinked${NC} ${DIM}.cursor/skills${NC}"
        if [ -f "$REPO_ROOT/AGENTS.md" ]; then
            cp "$REPO_ROOT/AGENTS.md" "$REPO_ROOT/.cursorrules"
            echo -e "${GREEN}     📝 Copied${NC} ${DIM}AGENTS.md → .cursorrules${NC}"
        fi
    fi
}

setup_opencode() {
    echo -e "${BLUE}   🔵 OpenCode${NC}"
    if [ "$SETUP_GLOBAL" = true ]; then
        create_skills_symlink "$HOME/.config/opencode/skills" "$HOME/.config/opencode"
        [ ! -L "$HOME/.config/opencode/skills" ] && echo -e "${GREEN}     🔗 Symlinked${NC} ${DIM}~/.config/opencode/skills${NC}"
        echo -e "${GREEN}     ✅ OpenCode uses AGENTS.md natively${NC}"
    else
        create_skills_symlink "$REPO_ROOT/.opencode/skills" "$REPO_ROOT/.opencode"
        [ ! -L "$REPO_ROOT/.opencode/skills" ] && echo -e "${GREEN}     🔗 Symlinked${NC} ${DIM}.opencode/skills${NC}"
        echo -e "${GREEN}     ✅ OpenCode uses AGENTS.md natively${NC}"
    fi
}

setup_gemini() {
    echo -e "${RED}   🔴 Gemini CLI${NC}"
    if [ "$SETUP_GLOBAL" = true ]; then
        create_skills_symlink "$HOME/.gemini/skills" "$HOME/.gemini"
        [ ! -L "$HOME/.gemini/skills" ] && echo -e "${GREEN}     🔗 Symlinked${NC} ${DIM}~/.gemini/skills${NC}"
        if [ -f "$REPO_ROOT/AGENTS.md" ]; then
            cp "$REPO_ROOT/AGENTS.md" "$HOME/GEMINI.md"
            echo -e "${GREEN}     📝 Copied${NC} ${DIM}AGENTS.md → ~/GEMINI.md${NC}"
        fi
    else
        create_skills_symlink "$REPO_ROOT/.gemini/skills" "$REPO_ROOT/.gemini"
        [ ! -L "$REPO_ROOT/.gemini/skills" ] && echo -e "${GREEN}     🔗 Symlinked${NC} ${DIM}.gemini/skills${NC}"
        copy_agents_md "GEMINI.md" "$REPO_ROOT"
    fi
}

setup_copilot() {
    echo -e "${YELLOW}   🟠 GitHub Copilot${NC}"
    if [ "$SETUP_GLOBAL" = true ]; then
        echo -e "${YELLOW}     ⚠️  Project-only. Skipped globally.${NC}"
        return 0
    fi
    if [ -f "$REPO_ROOT/AGENTS.md" ]; then
        mkdir -p "$REPO_ROOT/.github"
        cp "$REPO_ROOT/AGENTS.md" "$REPO_ROOT/.github/copilot-instructions.md"
        echo -e "${GREEN}     📝 Copied${NC} ${DIM}AGENTS.md → .github/copilot-instructions.md${NC}"
    else
        echo -e "${YELLOW}     ⚠️  No root AGENTS.md found${NC}"
    fi
}

# ─── Argument Parsing ────────────────────────────────────────────────

while [ $# -gt 0 ]; do
    case $1 in
        --all)
            SETUP_CLAUDE=true
            SETUP_CURSOR=true
            SETUP_OPENCODE=true
            SETUP_GEMINI=true
            SETUP_COPILOT=true
            shift
            ;;
        --global)
            SETUP_GLOBAL=true
            shift
            ;;
        --claude) SETUP_CLAUDE=true; shift ;;
        --cursor) SETUP_CURSOR=true; shift ;;
        --opencode) SETUP_OPENCODE=true; shift ;;
        --gemini) SETUP_GEMINI=true; shift ;;
        --copilot) SETUP_COPILOT=true; shift ;;
        --help|-h)
            show_help
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            show_help
            exit 1
            ;;
    esac
done

# ─── Main ────────────────────────────────────────────────────────────

local_scope="project"
[ "$SETUP_GLOBAL" = true ] && local_scope="global"

print_banner

SKILL_COUNT=0
while IFS= read -r _skill_file; do
    [ -z "$_skill_file" ] && continue
    SKILL_COUNT=$((SKILL_COUNT + 1))
done <<EOF
$(find "$SKILLS_SOURCE" -mindepth 2 -maxdepth 2 -name "SKILL.md" 2>/dev/null)
EOF

if [ "$SKILL_COUNT" -eq 0 ]; then
    echo -e "${RED}❌ No skills found in $SKILLS_SOURCE${NC}"
    exit 1
fi

if [ "$USE_COPY" = true ]; then
    echo -e "   ${DIM}Detected Windows environment — using file copies instead of symlinks${NC}"
    echo ""
fi

echo -e "   ${DIM}Found${NC} ${BOLD}$SKILL_COUNT${NC} ${DIM}skills to configure${NC}"
echo ""

if [ "$SETUP_CLAUDE" = false ] && [ "$SETUP_CURSOR" = false ] && \
   [ "$SETUP_OPENCODE" = false ] && [ "$SETUP_GEMINI" = false ] && \
   [ "$SETUP_COPILOT" = false ]; then
    show_menu
    echo ""
fi

if [ "$SETUP_CLAUDE" = false ] && [ "$SETUP_CURSOR" = false ] && \
   [ "$SETUP_OPENCODE" = false ] && [ "$SETUP_GEMINI" = false ] && \
   [ "$SETUP_COPILOT" = false ]; then
    echo -e "${YELLOW}⚠️  No AI assistants selected. Nothing to do.${NC}"
    exit 0
fi

# ─── Progress Bar ────────────────────────────────────────────────────

TOTAL=0
[ "$SETUP_CLAUDE" = true ] && TOTAL=$((TOTAL + 1))
[ "$SETUP_CURSOR" = true ] && TOTAL=$((TOTAL + 1))
[ "$SETUP_OPENCODE" = true ] && TOTAL=$((TOTAL + 1))
[ "$SETUP_GEMINI" = true ] && TOTAL=$((TOTAL + 1))
[ "$SETUP_COPILOT" = true ] && TOTAL=$((TOTAL + 1))

STEP=1

[ "$SETUP_CLAUDE" = true ] && { echo -e "\n${CYAN}   ── Step $STEP/$TOTAL ──${NC}"; setup_claude; STEP=$((STEP + 1)); }
[ "$SETUP_CURSOR" = true ] && { echo -e "\n${CYAN}   ── Step $STEP/$TOTAL ──${NC}"; setup_cursor; STEP=$((STEP + 1)); }
[ "$SETUP_OPENCODE" = true ] && { echo -e "\n${CYAN}   ── Step $STEP/$TOTAL ──${NC}"; setup_opencode; STEP=$((STEP + 1)); }
[ "$SETUP_GEMINI" = true ] && { echo -e "\n${CYAN}   ── Step $STEP/$TOTAL ──${NC}"; setup_gemini; STEP=$((STEP + 1)); }
[ "$SETUP_COPILOT" = true ] && { echo -e "\n${CYAN}   ── Step $STEP/$TOTAL ──${NC}"; setup_copilot; }

# ─── Summary ─────────────────────────────────────────────────────────

resolve_path() {
    local path="$1"
    if [ -L "$path" ]; then
        local link
        link=$(readlink "$path" 2>/dev/null) || link=$(ls -l "$path" | awk '{print $NF}')
        echo "$path → $link"
    else
        echo "$path"
    fi
}

echo ""
print_box "$GREEN" "🎉" "Installation Complete — $SKILL_COUNT skills configured"
echo ""

echo -e "${DIM}   Installed locations ($local_scope):${NC}"
echo ""

if [ "$SETUP_GLOBAL" = true ]; then
    [ "$SETUP_CLAUDE" = true ] && echo -e "   🟣 Claude Code    ${DIM}$(resolve_path "$HOME/.claude/skills")${NC}" && echo -e "                    ${DIM}$(resolve_path "$HOME/CLAUDE.md")${NC}"
    [ "$SETUP_CURSOR" = true ] && echo -e "   ⚫ Cursor         ${DIM}$(resolve_path "$HOME/.cursor/skills")${NC}" && echo -e "                    ${DIM}$(resolve_path "$HOME/.cursorrules")${NC}"
    [ "$SETUP_OPENCODE" = true ] && echo -e "   🔵 OpenCode       ${DIM}$(resolve_path "$HOME/.config/opencode/skills")${NC}"
    [ "$SETUP_GEMINI" = true ] && echo -e "   🔴 Gemini CLI     ${DIM}$(resolve_path "$HOME/.gemini/skills")${NC}" && echo -e "                    ${DIM}$(resolve_path "$HOME/GEMINI.md")${NC}"
    [ "$SETUP_COPILOT" = true ] && echo -e "   🟠 GitHub Copilot ${YELLOW}project-only (skipped globally)${NC}"
else
    [ "$SETUP_CLAUDE" = true ] && echo -e "   🟣 Claude Code    ${DIM}$(resolve_path "$REPO_ROOT/.claude/skills")${NC}" && echo -e "                    ${DIM}$(resolve_path "$REPO_ROOT/CLAUDE.md")${NC}"
    [ "$SETUP_CURSOR" = true ] && echo -e "   ⚫ Cursor         ${DIM}$(resolve_path "$REPO_ROOT/.cursor/skills")${NC}" && echo -e "                    ${DIM}$(resolve_path "$REPO_ROOT/.cursorrules")${NC}"
    [ "$SETUP_OPENCODE" = true ] && echo -e "   🔵 OpenCode       ${DIM}$(resolve_path "$REPO_ROOT/.opencode/skills")${NC}" && echo -e "                    ${DIM}$(resolve_path "$REPO_ROOT/AGENTS.md")${NC} ${DIM}(native)${NC}"
    [ "$SETUP_GEMINI" = true ] && echo -e "   🔴 Gemini CLI     ${DIM}$(resolve_path "$REPO_ROOT/.gemini/skills")${NC}" && echo -e "                    ${DIM}$(resolve_path "$REPO_ROOT/GEMINI.md")${NC}"
    [ "$SETUP_COPILOT" = true ] && echo -e "   🟠 GitHub Copilot ${DIM}$(resolve_path "$REPO_ROOT/.github/copilot-instructions.md")${NC}"
fi

echo ""
echo -e "${CYAN}┌────────────────────────────────────────────────────────────┐${NC}"
echo -e "${CYAN}│${NC}  💡 ${BOLD}Next step:${NC} Restart your AI assistant to load the skills     ${CYAN}│${NC}"
echo -e "${CYAN}│${NC}  📝 ${BOLD}Pro tip:${NC}  AGENTS.md is the source of truth — edit it,    ${CYAN}│${NC}"
echo -e "${CYAN}│${NC}            then re-run this script to sync changes        ${CYAN}│${NC}"
echo -e "${CYAN}└────────────────────────────────────────────────────────────┘${NC}"
echo ""
