#!/usr/bin/env bash
# Generated by project-knowledge-bootstrap v1.0
# Version: 1.0
# Sync skill metadata to AGENTS.md Auto-invoke sections
# Reads SKILL.md frontmatter from all skills and generates Auto-invoke tables.
#
# Usage:
#   ./sync.sh              # Update all AGENTS.md files
#   ./sync.sh --dry-run    # Show what would change
#   ./sync.sh --scope root # Only update root AGENTS.md
#
# Compatible with Bash 3+ (macOS default)
# Idempotent: running multiple times produces identical output

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Navigate to repo root from skills/skill-sync/assets/
REPO_ROOT="$(dirname "$(dirname "$(dirname "$SCRIPT_DIR")")")"
SKILLS_DIR="$REPO_ROOT/skills"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Options
DRY_RUN=false
FILTER_SCOPE=""

# Parse arguments
while [ $# -gt 0 ]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --scope)
            FILTER_SCOPE="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 [--dry-run] [--scope <scope>]"
            echo ""
            echo "Syncs skill metadata to AGENTS.md Auto-invoke sections."
            echo ""
            echo "Options:"
            echo "  --dry-run    Show what would change without modifying files"
            echo "  --scope      Only sync specific scope (e.g., root, ui, api)"
            echo ""
            echo "Scope mapping is auto-detected from the project structure."
            echo "Root AGENTS.md is always at the repo root."
            echo "Component AGENTS.md files are detected by scanning for"
            echo "directories that contain their own AGENTS.md."
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# =============================================================================
# SCOPE MAPPING
# =============================================================================
# Map scope values to AGENTS.md file paths.
# 'root' always maps to the repo root. Other scopes are auto-detected
# by scanning for directories that contain AGENTS.md files.
#
# To customize: edit the get_agents_path function below.

get_agents_path() {
    local scope="$1"
    case "$scope" in
        root) echo "$REPO_ROOT/AGENTS.md" ;;
        *)
            # Auto-detect: check if a directory matching the scope name exists
            # and has an AGENTS.md file
            if [ -f "$REPO_ROOT/$scope/AGENTS.md" ]; then
                echo "$REPO_ROOT/$scope/AGENTS.md"
            else
                echo ""
            fi
            ;;
    esac
}

# =============================================================================
# FRONTMATTER PARSING
# =============================================================================

# Extract a top-level YAML frontmatter field
extract_field() {
    local file="$1"
    local field="$2"
    awk -v field="$field" '
        /^---$/ { in_frontmatter = !in_frontmatter; next }
        in_frontmatter && $1 == field":" {
            sub(/^[^:]+:[[:space:]]*/, "")
            if ($0 != "" && $0 != ">") {
                gsub(/^["'"'"']|["'"'"']$/, "")
                print
                exit
            }
            getline
            while (/^[[:space:]]/ && !/^---$/) {
                sub(/^[[:space:]]+/, "")
                printf "%s ", $0
                if (!getline) break
            }
            print ""
            exit
        }
    ' "$file" | sed 's/[[:space:]]*$//'
}

# Extract a nested metadata field (supports single value or YAML list)
# Returns pipe-delimited string for lists: "Action A|Action B"
extract_metadata() {
    local file="$1"
    local field="$2"

    awk -v field="$field" '
        function trim(s) {
            sub(/^[[:space:]]+/, "", s)
            sub(/[[:space:]]+$/, "", s)
            return s
        }

        /^---$/ { in_frontmatter = !in_frontmatter; next }

        in_frontmatter && /^metadata:/ { in_metadata = 1; next }
        in_frontmatter && in_metadata && /^[a-z]/ && !/^[[:space:]]/ { in_metadata = 0 }

        in_frontmatter && in_metadata && $1 == field":" {
            sub(/^[^:]+:[[:space:]]*/, "")

            # Single-line scalar
            if ($0 != "") {
                v = $0
                gsub(/^["'"'"']|["'"'"']$/, "", v)
                gsub(/^\[|\]$/, "", v)
                print trim(v)
                exit
            }

            # Multi-line list
            out = ""
            while (getline) {
                if (!in_frontmatter) break
                if (!in_metadata) break
                if ($0 ~ /^[a-z]/ && $0 !~ /^[[:space:]]/) break
                line = $0
                if (line ~ /^---$/) break
                if (line ~ /^[[:space:]]*-[[:space:]]*/) {
                    sub(/^[[:space:]]*-[[:space:]]*/, "", line)
                    line = trim(line)
                    gsub(/^["'"'"']|["'"'"']$/, "", line)
                    if (line != "") {
                        if (out == "") out = line
                        else out = out "|" line
                    }
                } else {
                    break
                }
            }

            if (out != "") print out
            exit
        }
    ' "$file"
}

# =============================================================================
# MAIN
# =============================================================================

echo -e "${BLUE}Skill Sync — Updating AGENTS.md Auto-invoke sections${NC}"
echo "========================================================"
echo ""

# Verify skills directory exists
if [ ! -d "$SKILLS_DIR" ]; then
    echo -e "${RED}Skills directory not found: $SKILLS_DIR${NC}"
    echo "Run this script from within a project that has a skills/ directory."
    exit 1
fi

# Collect skills by scope using temp files (Bash 3 compatible)
SCOPE_TMPDIR=$(mktemp -d)
trap 'rm -rf "$SCOPE_TMPDIR"' EXIT

# Deterministic iteration order (sorted for stable diffs)
while IFS= read -r skill_file; do
    [ -f "$skill_file" ] || continue

    skill_name=$(extract_field "$skill_file" "name")
    scope_raw=$(extract_metadata "$skill_file" "scope")
    auto_invoke_raw=$(extract_metadata "$skill_file" "auto_invoke")

    # Use ';;' as internal separator to avoid conflicts with '|'
    auto_invoke=$(echo "$auto_invoke_raw" | sed 's/|/;;/g')

    # Skip skills without scope or auto_invoke
    [ -z "$scope_raw" ] || [ -z "$auto_invoke" ] && continue

    # Parse scope (can be comma-separated, space-separated, or bracket-enclosed)
    echo "$scope_raw" | tr -d '[]' | tr ', ' '\n' | while read -r scope; do
        scope=$(echo "$scope" | tr -d '[:space:]')
        [ -z "$scope" ] && continue

        # Filter by scope if specified
        [ -n "$FILTER_SCOPE" ] && [ "$scope" != "$FILTER_SCOPE" ] && continue

        echo "$skill_name:$auto_invoke" >> "$SCOPE_TMPDIR/$scope"
    done
done <<EOF
$(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name SKILL.md -print 2>/dev/null | sort)
EOF

# Generate Auto-invoke section for each scope
UPDATED=0
for scope_file in "$SCOPE_TMPDIR"/*; do
    [ -f "$scope_file" ] || continue
    scope=$(basename "$scope_file")
    agents_path=$(get_agents_path "$scope")

    if [ -z "$agents_path" ] || [ ! -f "$agents_path" ]; then
        echo -e "${YELLOW}Warning: No AGENTS.md found for scope '$scope' (expected at: $agents_path)${NC}"
        continue
    fi

    echo -e "${BLUE}Processing: $scope -> $(echo "$agents_path" | sed "s|$REPO_ROOT/||")${NC}"

    # Build the Auto-invoke table
    auto_invoke_section="### Auto-invoke Skills

When performing these actions, ALWAYS invoke the corresponding skill FIRST:

| Action | Skill |
|--------|-------|"

    # Expand into sortable rows
    rows_file=$(mktemp)

    while IFS= read -r entry; do
        [ -z "$entry" ] && continue
        skill_name="${entry%%:*}"
        actions_raw="${entry#*:}"

        # Restore '|' from ';;' and split actions
        actions_raw=$(echo "$actions_raw" | sed 's/;;/|/g')
        echo "$actions_raw" | tr '|' '\n' | while read -r action; do
            action=$(echo "$action" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
            [ -z "$action" ] && continue
            printf "%s\t%s\n" "$action" "$skill_name" >> "$rows_file"
        done
    done < "$scope_file"

    # Sort rows deterministically (by Action then Skill)
    while IFS="$(printf '\t')" read -r action skill_name; do
        [ -z "$action" ] && continue
        auto_invoke_section="$auto_invoke_section
| $action | \`$skill_name\` |"
    done <<SORTED
$(LC_ALL=C sort -t "$(printf '\t')" -k1,1 -k2,2 "$rows_file")
SORTED

    # Add generation comment
    auto_invoke_section="$auto_invoke_section
<!-- Generated by skills/skill-sync/assets/sync.sh — DO NOT edit manually -->"

    rm -f "$rows_file"

    if $DRY_RUN; then
        echo -e "${YELLOW}[DRY RUN] Would update $(echo "$agents_path" | sed "s|$REPO_ROOT/||"):${NC}"
        echo "$auto_invoke_section"
        echo ""
    else
        # Write new section to temp file
        section_file=$(mktemp)
        echo "$auto_invoke_section" > "$section_file"

        if grep -q "### Auto-invoke Skills" "$agents_path"; then
            # Replace existing section (up to next --- or ## heading)
            awk '
                /^### Auto-invoke Skills/ {
                    while ((getline line < "'"$section_file"'") > 0) print line
                    close("'"$section_file"'")
                    skip = 1
                    next
                }
                skip && /^(---|## |### [^A])/ {
                    skip = 0
                    print ""
                }
                !skip { print }
            ' "$agents_path" > "$agents_path.tmp"
            mv "$agents_path.tmp" "$agents_path"
            echo -e "${GREEN}  ✓ Updated Auto-invoke section${NC}"
        else
            # Append before the last --- separator, or at end of file
            if grep -q "^---$" "$agents_path"; then
                # Insert before the LAST --- separator
                awk -v section_file="$section_file" '
                    { lines[NR] = $0 }
                    /^---$/ { last_sep = NR }
                    END {
                        for (i = 1; i <= NR; i++) {
                            if (i == last_sep) {
                                print ""
                                while ((getline line < section_file) > 0) print line
                                close(section_file)
                                print ""
                            }
                            print lines[i]
                        }
                    }
                ' "$agents_path" > "$agents_path.tmp"
            else
                # No separator found, append at end
                cp "$agents_path" "$agents_path.tmp"
                echo "" >> "$agents_path.tmp"
                cat "$section_file" >> "$agents_path.tmp"
            fi
            mv "$agents_path.tmp" "$agents_path"
            echo -e "${GREEN}  ✓ Inserted Auto-invoke section${NC}"
        fi

        rm -f "$section_file"
        UPDATED=$((UPDATED + 1))
    fi
done

echo ""
if $DRY_RUN; then
    echo -e "${YELLOW}Dry run complete. No files modified.${NC}"
else
    echo -e "${GREEN}Done! Updated $UPDATED AGENTS.md file(s).${NC}"
fi

# Show skills missing metadata
echo ""
echo -e "${BLUE}Skills missing sync metadata:${NC}"
missing=0
while IFS= read -r skill_file; do
    [ -f "$skill_file" ] || continue
    skill_name=$(extract_field "$skill_file" "name")
    scope_raw=$(extract_metadata "$skill_file" "scope")
    auto_invoke_raw=$(extract_metadata "$skill_file" "auto_invoke")

    if [ -z "$scope_raw" ] || [ -z "$auto_invoke_raw" ]; then
        missing_fields=""
        [ -z "$scope_raw" ] && missing_fields="scope"
        [ -z "$auto_invoke_raw" ] && { [ -n "$missing_fields" ] && missing_fields="$missing_fields, "; missing_fields="${missing_fields}auto_invoke"; }
        echo -e "  ${YELLOW}${skill_name:-unknown}${NC} — missing: $missing_fields"
        missing=$((missing + 1))
    fi
done <<EOF
$(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name SKILL.md -print 2>/dev/null | sort)
EOF

if [ $missing -eq 0 ]; then
    echo -e "  ${GREEN}All skills have sync metadata${NC}"
fi
